//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAD_Editor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAD_Editor.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Line.
        /// </summary>
        internal static string AddLine {
            get {
                return ResourceManager.GetString("AddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set By Axis.
        /// </summary>
        internal static string CameraSetViewByAxis {
            get {
                return ResourceManager.GetString("CameraSetViewByAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string Colon_Symbol {
            get {
                return ResourceManager.GetString("Colon_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Attaching.
        /// </summary>
        internal static string ContextMenu_AttachingItem {
            get {
                return ResourceManager.GetString("ContextMenu_AttachingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube.
        /// </summary>
        internal static string ContextMenu_CreateCubeBrickElementItem {
            get {
                return ResourceManager.GetString("ContextMenu_CreateCubeBrickElementItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string ContextMenu_CreateItem {
            get {
                return ResourceManager.GetString("ContextMenu_CreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pyramid.
        /// </summary>
        internal static string ContextMenu_CreatePyramidBrickElementItem {
            get {
                return ResourceManager.GetString("ContextMenu_CreatePyramidBrickElementItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sphere.
        /// </summary>
        internal static string ContextMenu_CreateSphereBrickElementItem {
            get {
                return ResourceManager.GetString("ContextMenu_CreateSphereBrickElementItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ContextMenu_DeleteItem {
            get {
                return ResourceManager.GetString("ContextMenu_DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide.
        /// </summary>
        internal static string ContextMenu_DivideItem {
            get {
                return ResourceManager.GetString("ContextMenu_DivideItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset Attaching.
        /// </summary>
        internal static string ContextMenu_NotAttachingItem {
            get {
                return ResourceManager.GetString("ContextMenu_NotAttachingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unset Target.
        /// </summary>
        internal static string ContextMenu_NotTargetItem {
            get {
                return ResourceManager.GetString("ContextMenu_NotTargetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Target.
        /// </summary>
        internal static string ContextMenu_TargetItem {
            get {
                return ResourceManager.GetString("ContextMenu_TargetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube Brick Element.
        /// </summary>
        internal static string CreatingComponent {
            get {
                return ResourceManager.GetString("CreatingComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter valid values of line&apos;s coordianates.
        /// </summary>
        internal static string Error_PleaseEnterValidCoords {
            get {
                return ResourceManager.GetString("Error_PleaseEnterValidCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select a line and enter updated coordinates.
        /// </summary>
        internal static string Error_PleaseEnterValidLine {
            get {
                return ResourceManager.GetString("Error_PleaseEnterValidLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitMenu {
            get {
                return ResourceManager.GetString("ExitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ExportMenu {
            get {
                return ResourceManager.GetString("ExportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object is exported successfully.
        /// </summary>
        internal static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create with.
        /// </summary>
        internal static string FiguresMenuItem_CreateWith {
            get {
                return ResourceManager.GetString("FiguresMenuItem_CreateWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string FiguresMenuItem_CreateWithLine {
            get {
                return ResourceManager.GetString("FiguresMenuItem_CreateWithLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hollow Object.
        /// </summary>
        internal static string FiguresMenuItem_CustomHollowObject {
            get {
                return ResourceManager.GetString("FiguresMenuItem_CustomHollowObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Custom.
        /// </summary>
        internal static string FiguresMenuItem_CustomObjects {
            get {
                return ResourceManager.GetString("FiguresMenuItem_CustomObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface.
        /// </summary>
        internal static string FiguresMenuItem_CustomSurface {
            get {
                return ResourceManager.GetString("FiguresMenuItem_CustomSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hollow Objects.
        /// </summary>
        internal static string FiguresMenuItem_HollowObjects {
            get {
                return ResourceManager.GetString("FiguresMenuItem_HollowObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid Objects.
        /// </summary>
        internal static string FiguresMenuItem_SolidObjects {
            get {
                return ResourceManager.GetString("FiguresMenuItem_SolidObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string MenuItem_Camera {
            get {
                return ResourceManager.GetString("MenuItem_Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figures.
        /// </summary>
        internal static string MenuItem_Figures {
            get {
                return ResourceManager.GetString("MenuItem_Figures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MenuItem_File {
            get {
                return ResourceManager.GetString("MenuItem_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene.
        /// </summary>
        internal static string MenuItem_Scene {
            get {
                return ResourceManager.GetString("MenuItem_Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJ.
        /// </summary>
        internal static string ObjFormat {
            get {
                return ResourceManager.GetString("ObjFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenMenu {
            get {
                return ResourceManager.GetString("OpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Properties_Size {
            get {
                return ResourceManager.GetString("Properties_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Foundation Size.
        /// </summary>
        internal static string Properties_Size_DownFoundationSize {
            get {
                return ResourceManager.GetString("Properties_Size_DownFoundationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Properties_Size_Height {
            get {
                return ResourceManager.GetString("Properties_Size_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        internal static string Properties_Size_Radius {
            get {
                return ResourceManager.GetString("Properties_Size_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Foundation Size.
        /// </summary>
        internal static string Properties_Size_TopFoundationSize {
            get {
                return ResourceManager.GetString("Properties_Size_TopFoundationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating.
        /// </summary>
        internal static string PropertiesTabControl_Creating {
            get {
                return ResourceManager.GetString("PropertiesTabControl_Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string PropertiesTabControl_Properties {
            get {
                return ResourceManager.GetString("PropertiesTabControl_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimisation.
        /// </summary>
        internal static string PropertiesTabControl_Render {
            get {
                return ResourceManager.GetString("PropertiesTabControl_Render", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Property_Name {
            get {
                return ResourceManager.GetString("Property_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Property_Position {
            get {
                return ResourceManager.GetString("Property_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Line.
        /// </summary>
        internal static string RemoveLine {
            get {
                return ResourceManager.GetString("RemoveLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing.
        /// </summary>
        internal static string Render_Drawing {
            get {
                return ResourceManager.GetString("Render_Drawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faces.
        /// </summary>
        internal static string Render_Drawing_Faces {
            get {
                return ResourceManager.GetString("Render_Drawing_Faces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw All Faces.
        /// </summary>
        internal static string Render_Drawing_TriangleFaces {
            get {
                return ResourceManager.GetString("Render_Drawing_TriangleFaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Lables.
        /// </summary>
        internal static string Render_Drawing_VertexIndices {
            get {
                return ResourceManager.GetString("Render_Drawing_VertexIndices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveMenu {
            get {
                return ResourceManager.GetString("SaveMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Mode.
        /// </summary>
        internal static string SceneMode_EditMode {
            get {
                return ResourceManager.GetString("SceneMode_EditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Mode.
        /// </summary>
        internal static string SceneMode_ViewMode {
            get {
                return ResourceManager.GetString("SceneMode_ViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Line.
        /// </summary>
        internal static string UpdateLine {
            get {
                return ResourceManager.GetString("UpdateLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string X_Coordinate {
            get {
                return ResourceManager.GetString("X_Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Y_Coordinate {
            get {
                return ResourceManager.GetString("Y_Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        internal static string Z_Coordinate {
            get {
                return ResourceManager.GetString("Z_Coordinate", resourceCulture);
            }
        }
    }
}
